README.md

the tables were too wide for GitHub, so this should help with readability

docs: separate origin urls into a separate table

---

frontend/src/components/Home.js

specifically: getting started, contributing, list of proofs, tutorial video

feat(frontend): add links to homepage

---

README.md
backend/db.js
backend/package-lock.json
backend/package.json

Always check for updates, regardless of successful update check or not

Add resilience to auto-updater

---

backend/api.js
backend/db.js
frontend/src/App.js
frontend/src/components/Home.css
frontend/src/components/Home.js
frontend/src/lib/consts.js

Read version number from local package and show it on homepage.
**Updated Screenshot** <img width="1232" alt="image" src="https://user-images.githubusercontent.com/44710980/87253298-c7113980-c43f-11ea-86b6-7c8c286b014e.png">
1.5 hours
Fix #148 
@Harjot1Singh @bhajneet

feat: show version number on homepage

---

package-lock.json
package.json

brief_summary_plz
- none_whatsoever
nine_thousand_years
Fix #
@

build: bump to v1.2.0

---

CONTRIBUTING.md
backend/db.js
backend/package-lock.json
backend/package.json
backend/translate.js
frontend/package-lock.json
frontend/package.json
frontend/src/App.js
frontend/src/components/LineView.js
frontend/src/components/TranslationBlock.js

Adds Google Translate integration to Punjabi translations and additional notes. Also adds caching + prefetching for previous + next lines.
- 4 hours
@saihaj @bhajneet

feat: add Google Translate integration to translations

---

.gitignore
backend/.eslintrc
cypress.json
cypress/fixtures/example.json
cypress/integration/gh-issue-open.spec.js
cypress/integration/main.spec.js
cypress/plugins/index.js
cypress/support/commands.js
cypress/support/index.js
frontend/src/components/LineView.js
package-lock.json
package.json

Setup E2E tests. Originally in #309 but splitting it up to make it easy.
Tests work!
See #309 
@Harjot1Singh

test: add e2e tests using cypress

---

frontend/src/media/logo.svg

Use new brand logo with gradient background
128 seconds
@saihaj

feat: update logo

---

frontend/src/components/SourceView.js

Using next and previous lines will now vertically center the screen on the line.
- Tab/arrow hotkeys
- Clicking on line and using parent button
- Focusing a line, scrolling away, hitting enter, and using parent button
15 mins
@Harjot1Singh

feat: center/scroll viewport on active/focus line

---

.github/workflows/release.yml

brief_summary_plz
- none_whatsoever
nine_thousand_years
Fix #

build: test manual workflow for release

---

backend/Dockerfile
frontend/Dockerfile

Should temporarily fix react scripts not found issues

ci: replace npm ci with npm install

---

backend/package-lock.json
backend/package.json
frontend/package-lock.json
frontend/package.json

Updating `react-scripts` fixes not found issue so frontend should build now

build: update dependencies

---

.github/workflows/continuous-integration.yml
.github/workflows/release-latest.yml

This allows the release to be only run from a manual workflow dispatch and actually create a release.

ci: enable full release pipeline

---

.github/workflows/release.yml

build: rename database-viewer image to viewer

---

frontend/src/screens/SourceView.tsx

fix: show scrollbars as needed

---

cypress/support/commands.ts
frontend/src/screens/SourceView.tsx

fix: remove initial space on lines in source view

---

frontend/src/App.tsx
frontend/src/screens/404.tsx

feat: add routes for partial matches and no matches

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/Modal.tsx
frontend/src/components/Nav.tsx
frontend/src/components/Slider.tsx
frontend/src/helpers/theme.ts
frontend/src/screens/About.tsx
frontend/src/screens/Interface.tsx
frontend/src/screens/SourceView.tsx

Converts about into a modal. Adds an "interface" modal. Changes zoom factor on source view.
- nr test
- nr lint
- mobile browser
- light / dark modes
- 2 hours (learning jotai)
Close #392

feat: add zoom slider to interface controls

---

frontend/src/components/Layout.tsx
frontend/src/screens/SourceView.tsx

fix: position bottom bar for mobile usage

---

frontend/src/components/AsciiGurmukhi.tsx
frontend/src/helpers/theme.ts
frontend/src/screens/Collections.tsx
frontend/src/screens/LineView.tsx
frontend/src/screens/SourceView.tsx

- rewrite asciigurmukhi for the future of "formattedgurmukhi" component
- add colors for vishrām in  light/dark themes

feat: add syntax colors to indicate pauses in source
